
ebaydate_verify: dateData?.ebaydate_verify
? moment(dateData.ebay_date_verify).format("MM-DD-YYYY")
: "",

      ebaydate_start:dateData?.ebaydate_start? moment(dateData.ebaydate_start).format("MM-DD-YYYY"): "",
      ebaydate_verify:dateData?.ebaydate_verify? moment(dateData.ebaydate_verify).format("MM-DD-YYYY"): "",
      ebaydate_seller:dateData?.ebaydate_seller? moment(dateData.ebaydate_seller).format("MM-DD-YYYY"): "",
      ebaydate_nextclass:dateData?.ebaydate_nextclass? moment(dateData.ebaydate_nextclass).format("MM-DD-YYYY"): "",
      ebaydate_verifybank:dateData?.ebaydate_verifybank? moment(dateData.ebaydate_verifybank).format("MM-DD-YYYY"): "",
      ebaydate_draft:dateData?.ebaydate_draft? moment(dateData.ebaydate_draft).format("MM-DD-YYYY"): "",
      ebaydate_list1:dateData?.ebaydate_list1? moment(dateData.ebaydate_list1).format("MM-DD-YYYY"): "",
      ebaydate_list2:dateData?.ebaydate_list2? moment(dateData.ebaydate_list2).format("MM-DD-YYYY"): "",
      ebaydate_list3:dateData?.ebaydate_list3? moment(dateData.ebaydate_list3).format("MM-DD-YYYY"): "",
      ebaydate_list4:dateData?.ebaydate_list4? moment(dateData.ebaydate_list4).format("MM-DD-YYYY"): "",
      ebaydate_list5:dateData?.ebaydate_list5? moment(dateData.ebaydate_list5).format("MM-DD-YYYY"): "",
      ebaydate_expectedseller:dateData?.ebaydate_expectedseller? moment(dateData.ebaydate_expectedseller).format("MM-DD-YYYY"): "",
      ebaydate_expectedlist1:dateData?.ebaydate_expectedlist1? moment(dateData.ebaydate_expectedlist1).format("MM-DD-YYYY"): "",
      ebaydate_expectedlist2:dateData?.ebaydate_expectedlist2? moment(dateData.ebaydate_expectedlist2).format("MM-DD-YYYY"): "",
      ebaydate_expectedlist3:dateData?.ebaydate_expectedlist3? moment(dateData.ebaydate_expectedlist3).format("MM-DD-YYYY"): "",
      ebaydate_expectedlist4:dateData?.ebaydate_expectedlist4? moment(dateData.ebaydate_expectedlist4).format("MM-DD-YYYY"): "",
      ebaydate_expectedlist5:dateData?.ebaydate_expectedlist5? moment(dateData.ebaydate_expectedlist5).format("MM-DD-YYYY"): "",
      ebaydate_suspended:dateData?.ebaydate_suspended? moment(dateData.ebaydate_suspended).format("MM-DD-YYYY"): "",
      ebaydate_checksus:dateData?.ebaydate_checksus? moment(dateData.ebaydate_checksus).format("MM-DD-YYYY"): "",
      ebaydate_contact1:dateData?.ebaydate_contact1? moment(dateData.ebaydate_contact1).format("MM-DD-YYYY"): "",
      ebaydate_contact2:dateData?.ebaydate_contact2? moment(dateData.ebaydate_contact2).format("MM-DD-YYYY"): "",
      ebaydate_contact3:dateData?.ebaydate_contact3? moment(dateData.ebaydate_contact3).format("MM-DD-YYYY"): "",
      ebaydate_contact4:dateData?.ebaydate_contact4? moment(dateData.ebaydate_contact4).format("MM-DD-YYYY"): "",
      ebaydate_contact5:dateData?.ebaydate_contact5? moment(dateData.ebaydate_contact5).format("MM-DD-YYYY"): "",
      ebaydate_checksus1:dateData?.ebaydate_checksus1? moment(dateData.ebaydate_checksus1).format("MM-DD-YYYY"): "",
      ebaydate_checksus2:dateData?.ebaydate_checksus2? moment(dateData.ebaydate_checksus2).format("MM-DD-YYYY"): "",
      ebaydate_delivery: dateData?.ebaydate_delivery? moment(dateData.ebaydate_delivery).format("MM-DD-YYYY"): "",