export const listselect_employee = ["Thái Sơn","Quốc Tuấn","Tiến Anh"];

export const listselect_processing = [
    "Login mail",
    "Verify Mail",
    "Buyer",
    "View",
    "Like",
    "Policies",
    "Verify Full",
    "Avatar",
    "Add to cart",
    "Seller",
    "Verify Bank",
    "Draft",
    "List",
    "Sold",
    "Quảng cáo",
    "Above Standard",
    "Top Rate",
    "Restrict",
    "Suspended",
  ];

  export const listselect_plan = [
    "Phone",
    "PC",
    "Antidetect",
    "Gologin",
    "VPS",
    "Windows 10",
    "Windows 11",
    "MAC",
    "Ubuntu",
    "Chrome",
    "Firefox",
    "Edge",
    "Safari",
    "USB 4G",
    "Sproxy 4G",
    "Proxy",
    "Info real",
    "Info gen",
    "Sim real",
    "Sim otp",
    "Bank real",
    "Bank gen",
    "Quy trình 1",
    "Quy trình 2",
    "Quy trình 3",
    "Quy trình 4",
    "Quy trình 5",
    "Quy trình 6",
    "Quy trình 7",
    "Quy trình 8",
    "Quy trình 9",
    "Quy trình 10",
    "Quy trình 11",
    "Quy trình 12",
  ];
